#ifndef PQRASCV_H
#define PQRASCV_H

/* THIS FILE IS AUTO-GENERATED BY cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// FFI status codes returned by all pqrascv_* functions.
typedef enum PqrascvStatus {
    // Operation succeeded.
    Ok = 0,
    // A required pointer argument was null.
    ErrorNullPtr = 1,
    // Output buffer was too small.
    ErrorBufferTooSmall = 2,
    // Cryptographic operation failed.
    ErrorCrypto = 3,
    // Internal error.
    ErrorInternal = 4,
} PqrascvStatus;

// Generate a new ML-DSA-65 keypair.
//
// `signing_key_out` must be at least 32 bytes (ML_DSA_65_SEED_SIZE).
// `verifying_key_out` must be at least 1952 bytes (ML_DSA_65_VERIFYING_KEY_SIZE).
// On success, `*sk_len_out` and `*vk_len_out` are set to the actual sizes.
// On `PQRASCV_ERROR_BUFFER_TOO_SMALL`, they are set to the required sizes.
//
// # Safety
// All pointers must be non-null and valid for the given lengths.
enum PqrascvStatus pqrascv_generate_keypair(uint8_t *signing_key_out,
                                            uintptr_t *sk_len_out,
                                            uint8_t *verifying_key_out,
                                            uintptr_t *vk_len_out);

// Sign `message_ptr[0..message_len]` with the ML-DSA-65 signing seed.
//
// `signing_key_ptr` must point to at least `ML_DSA_65_SEED_SIZE` (32) bytes.
// `signature_out` must be at least 3309 bytes (ML_DSA_65_SIGNATURE_SIZE).
//
// # Safety
// All pointers must be non-null and valid for the specified lengths.
enum PqrascvStatus pqrascv_sign(const uint8_t *signing_key_ptr,
                                uintptr_t signing_key_len,
                                const uint8_t *message_ptr,
                                uintptr_t message_len,
                                uint8_t *signature_out,
                                uintptr_t *sig_len_out);

// Verify an ML-DSA-65 signature.
//
// Returns `PQRASCV_OK` if valid, `PQRASCV_ERROR_CRYPTO` if invalid.
//
// # Safety
// All pointers must be non-null and valid for the specified lengths.
enum PqrascvStatus pqrascv_verify(const uint8_t *verifying_key_ptr,
                                  uintptr_t verifying_key_len,
                                  const uint8_t *message_ptr,
                                  uintptr_t message_len,
                                  const uint8_t *signature_ptr,
                                  uintptr_t signature_len);

#endif /* PQRASCV_H */
